### ISSUE TITLE
Uncaught ReferenceError: alertify is not defined

### ISSUE THREAD

**Issue by OmarMAbbasi** [pazindorb/dc20rpg#11]
Getting an import error when trying to initialize the game state: 

```
fvtt_script.js:212 Uncaught ReferenceError: alertify is not defined
    at initializeAlertify (fvtt_script.js:212:5)
    at fvtt_script.js:4269:1
    at fvtt_script.js:4271:3
```

**Comment by OmarMAbbasi** [comment]
This turned out to be an issue with forge. Closing this out.
